### PR TITLE
testing using Test Kitchen, testinfra, and Docker

### PR DESCRIPTION
**Pull request by blbradley**
I made a test suite! I did this to [docker-formula](https://github.com/saltstack-formulas/docker-formula) also with great success.

I have been starting with Ubuntu 14.04 while implementing these test suites, but this formula has some problems on that OS. So, Debian Jessie is first here.

Need one review please.

### CODE REVIEW

**Comment by blbradley** [comment]
@aboe76 Hey! We do need some help over here.

**Comment by blbradley** [comment]
Don't forget to squash and merge!

**Comment by aboe76** [comment]
@blbradley thanks,

**Comment by blbradley** [comment]
Thank you! I've got another one coming soon.

**Comment by aboe76** [comment]
@blbradley will you create the 5.x installation also possible for this?

**Comment by blbradley** [comment]
That is the other one coming!

**Comment by aboe76** [comment]
@blbradley sweet 👍

**Comment by blbradley** [comment]
:grin:

**Pull request merged**
