### PR TITLE
add default for kibana:config pillar

### LINKED ISSUE #3: kibana.config fails with no pillar value
Error:
```
"Rendering SLS 'base:kibana.config' failed: Jinja variable 'dict object' has no attribute 'config'"
```

Working on a reasonable fix now.

### PR DESCRIPTION
**Pull request by blbradley**
Fixes #3.

I have tested this on Debian Jessie with no pillar data.

### CODE REVIEW

**Comment by blbradley** [comment]
Looking for one review. I can merge it myself.

**Comment by blbradley** [comment]
@martinhoefling @babilen ping!

**Comment by wwentland** [comment]
Sorry, just to understand the background of this: Why is this necessary/advantageous?

**Comment by blbradley** [comment]
It is necessary for the formula to work without any pillar data.

**Comment by meyerbro** [comment]
I had an issue with that today and believe this can be nice to be merged.

**Review by meyerbro — APPROVED** [review]

**Comment by blbradley** [comment]
@babilen Any problems?

**Comment by blbradley** [comment]
I'm going to merge this since @meyerbro approves and is a contributor.

**Comment by wwentland** [comment]
Thanks!

**Pull request merged**
